import React, { useState, useCallback } from 'react';
import { OperationList, OperationDetailModal } from '@system/features/system/components/operations';
import type { SystemTask } from '@system/features/system/types/system.types';

// Phase B.3 — Operations hub tab. Read-only task queue viewer (system
// operations are auto-generated by fleet autonomy + manual ops, not
// created by operators here). No page-level actions.
export const TasksTab: React.FC = () => {
  const [showDetailModal, setShowDetailModal] = useState(false);
  const [selectedOperationId, setSelectedOperationId] = useState<string | null>(null);

  const handleView = useCallback((op: SystemTask) => {
    setSelectedOperationId(op.id);
    setShowDetailModal(true);
  }, []);

  return (
    <>
      <OperationList onView={handleView} />
      <OperationDetailModal
        operationId={selectedOperationId}
        isOpen={showDetailModal}
        onClose={() => {
          setShowDetailModal(false);
          setSelectedOperationId(null);
        }}
      />
    </>
  );
};
