# frozen_string_literal: true

module Api
  module V1
    module System
      module Webhooks
        # Inbound webhook from the build-package-module.yaml CI workflow.
        # The workflow signs each callback with HMAC-SHA256 over the raw
        # body using the closure-specific secret generated by
        # ModuleBuildDispatchService.generate_webhook_secret. We verify
        # the signature and route to PackageBuildWebhookService.
        #
        # Per `feedback_webhook_receivers` in CLAUDE.md: inbound webhooks
        # return 200/202 on processing errors, NEVER 500 (avoids provider
        # retry storms). We log internally and return 202 with an error
        # field for the CI workflow to record but not retry on.
        class PackageBuildController < ApplicationController
          skip_before_action :authenticate_request, raise: false
          skip_before_action :verify_authenticity_token, raise: false

          def receive
            raw_body = request.raw_post
            sig = request.headers["X-Powernode-Signature"]

            unless verify_signature(raw_body, sig)
              render_error("Signature verification failed", status: :unauthorized)
              return
            end

            payload = JSON.parse(raw_body)
            result = ::System::PackageBuildWebhookService.call(payload: payload)

            if result.success
              render_success(
                {
                  artifacts_created: result.artifacts_created,
                  versions_created:  result.versions_created,
                  modules_updated:   result.modules_updated
                },
                status: :accepted
              )
            else
              # Return 202 even on processing errors per webhook-receiver
              # rule — log internally, surface for CI workflow visibility.
              Rails.logger.error("[PackageBuildWebhook] processing errors: #{result.errors.inspect}")
              render_success(
                {
                  ok:     false,
                  errors: result.errors
                },
                status: :accepted
              )
            end
          rescue JSON::ParserError => e
            render_error("Invalid JSON: #{e.message}", status: :bad_request)
          rescue ::System::PackageBuildWebhookService::WebhookError => e
            render_error("Webhook validation error: #{e.message}", status: :unprocessable_entity)
          end

          private

          def verify_signature(body, signature)
            return false if signature.blank?

            closure_id = JSON.parse(body)["closure_id"] rescue nil
            return false if closure_id.blank?

            expected = OpenSSL::HMAC.hexdigest(
              "SHA256",
              ENV.fetch("POWERNODE_PACKAGE_BUILD_HMAC_KEY", "dev-package-build-secret"),
              closure_id
            )
            # Constant-time comparison
            ActiveSupport::SecurityUtils.secure_compare(expected, signature.to_s)
          rescue StandardError
            false
          end
        end
      end
    end
  end
end
