# frozen_string_literal: true

# Sdwan::NatCompiler — emits the nft `sdwan_nat_<8>` chain for one
# network: `type nat hook prerouting priority -100` containing one
# DNAT rule per enabled, resolvable Sdwan::PortMapping where this
# peer is the hub.
#
# Output is a Hash with a `ruleset` text field that the agent's
# nat_applier.go writes wholesale to a 0600 tempfile and atomically
# applies via `nft -f`. The chain shares the `inet powernode_sdwan`
# table with the slice 2 filter chain — same atomic apply, no cross-
# table coupling.
#
# Slice 7b of the SDWAN plan.
module Sdwan
  class NatCompiler
    PRIORITY = -100  # nat prerouting; runs before slice 2's forward chain

    def self.compile_for_peer(peer)
      new(peer).compile
    end

    def initialize(peer)
      @peer = peer
      @network = peer.network
    end

    def compile
      mappings = ::Sdwan::PortMapping
                   .enabled
                   .where(sdwan_network_id: @network.id, sdwan_peer_id: @peer.id)
                   .includes(:target_peer, :target_virtual_ip)
                   .to_a

      return empty_output if mappings.empty?

      table = "powernode_sdwan"
      chain = "sdwan_nat_#{network_short_id}"
      rule_lines = []
      skipped = []

      mappings.each do |m|
        target_addr = m.resolved_target_address
        if target_addr.blank?
          skipped << { id: m.id, name: m.name, reason: "target unresolved (VIP unassigned?)" }
          next
        end
        target_port = m.effective_target_port
        rule_lines << build_rule(m.protocol, m.listen_port, target_addr, target_port)
      end

      ruleset = render_ruleset(table: table, chain: chain, rule_lines: rule_lines)
      {
        table: table,
        chain: chain,
        rule_count: rule_lines.size,
        ruleset: ruleset,
        skipped: skipped,
        compiled_at: Time.current.iso8601
      }
    end

    private

    def empty_output
      { table: "powernode_sdwan", chain: "sdwan_nat_#{network_short_id}",
        rule_count: 0, ruleset: nil, skipped: [], compiled_at: Time.current.iso8601 }
    end

    def network_short_id
      @network.id.to_s.delete("-").first(8)
    end

    # nft DNAT rule. We bracket IPv6 addresses to disambiguate the port
    # separator, matching the same `dnat to [<addr>]:<port>` syntax nft
    # accepts on the wire. v4 addresses don't need the brackets but
    # accept them too, so we always bracket for consistency.
    def build_rule(protocol, listen_port, target_addr, target_port)
      bracketed = target_addr.include?(":") ? "[#{target_addr}]" : target_addr
      "    #{protocol} dport #{listen_port} dnat to #{bracketed}:#{target_port}"
    end

    def render_ruleset(table:, chain:, rule_lines:)
      <<~NFT
        # Powernode SDWAN — generated by Sdwan::NatCompiler
        # Network #{@network.id} hub #{@peer.id}
        # Slice 7b: hub DNAT for v4-only-client → overlay-service bridging.
        table inet #{table} {
          chain #{chain} {
            type nat hook prerouting priority #{PRIORITY}; policy accept;
        #{rule_lines.join("\n")}
          }
        }
      NFT
    end
  end
end
