package k3sd

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/nodealchemy/powernode-system/agent/internal/fsutil"
)

// DefaultPaths is the canonical on-disk layout K3s uses. Centralized
// here so tests can override individual paths via DaemonPaths struct.
type DaemonPaths struct {
	BinaryPath          string // /usr/local/bin/k3s (install marker)
	UninstallScriptPath string // /usr/local/bin/k3s-uninstall.sh (server)
	UninstallAgentPath  string // /usr/local/bin/k3s-agent-uninstall.sh
	KubeconfigPath      string // /etc/rancher/k3s/k3s.yaml (server)
	ServerTokenPath     string // /var/lib/rancher/k3s/server/node-token
	AgentEnvFilePath    string // /etc/systemd/system/k3s-agent.service.d/override.conf
}

var DefaultPaths = DaemonPaths{
	BinaryPath:          "/usr/local/bin/k3s",
	UninstallScriptPath: "/usr/local/bin/k3s-uninstall.sh",
	UninstallAgentPath:  "/usr/local/bin/k3s-agent-uninstall.sh",
	KubeconfigPath:      "/etc/rancher/k3s/k3s.yaml",
	ServerTokenPath:     "/var/lib/rancher/k3s/server/node-token",
	AgentEnvFilePath:    "/etc/systemd/system/k3s-agent.service.d/override.conf",
}

// ShellServerApplier is the production ServerApplier. Wraps os/exec
// for the curl-install + systemctl + version calls; file IO for
// reading kubeconfig + tokens.
//
// Idempotency contract:
//   HasInstalled        — stat BinaryPath; true iff exists + non-zero size
//   InstallK3sServer    — `curl -sfL https://get.k3s.io | sh -s - server`
//                         (k3s install script is itself idempotent)
//   IsRunning / Start / Stop — systemctl on `k3s.service`
//   Version             — parse `k3s --version` (returns
//                         "k3s version v1.30.4+k3s1 (abc123)")
//   CaptureBootstrapState — read kubeconfig + token files; return
//                          empty strings if not yet populated
//                          (k3s creates these on first successful boot)
//   Cleanup             — exec UninstallScriptPath if present
type ShellServerApplier struct {
	Paths DaemonPaths
	Unit  string // defaults to "k3s.service"
	Exec  func(ctx context.Context, name string, args ...string) ([]byte, error)
}

func NewShellServerApplier() *ShellServerApplier {
	return &ShellServerApplier{Paths: DefaultPaths, Unit: "k3s.service"}
}

func (s *ShellServerApplier) unit() string {
	if s.Unit == "" {
		return "k3s.service"
	}
	return s.Unit
}

func (s *ShellServerApplier) execCmd(ctx context.Context, name string, args ...string) ([]byte, error) {
	if s.Exec != nil {
		return s.Exec(ctx, name, args...)
	}
	cmd := exec.CommandContext(ctx, name, args...)
	out, err := cmd.Output()
	if err != nil {
		var ee *exec.ExitError
		if errors.As(err, &ee) {
			return out, fmt.Errorf("%s %s: %w (stderr: %s)", name,
				strings.Join(args, " "), err, strings.TrimSpace(string(ee.Stderr)))
		}
		return out, fmt.Errorf("%s %s: %w", name, strings.Join(args, " "), err)
	}
	return out, nil
}

func (s *ShellServerApplier) HasInstalled(_ context.Context) (bool, error) {
	st, err := os.Stat(s.Paths.BinaryPath)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, fmt.Errorf("stat %s: %w", s.Paths.BinaryPath, err)
	}
	return st.Size() > 0, nil
}

// InstallK3sServer runs the official upstream install script. This
// is the simplest path for a v1 — k3s.io publishes a curl-able
// installer that handles all platforms + arch. Phase 3 will replace
// this with a NodeModule artifact + apt for hermetic, reproducible
// installs.
//
// Bootstrap-config-derived flags (cfg.InstallArgs) are appended
// after the `sh -s -` delimiter so the install script forwards them
// into the systemd unit's ExecStart. Phase O4: passing
// CniPlugin=ovn_kubernetes appends `--flannel-backend=none
// --disable-network-policy` so K3s skips Flannel + kube-proxy
// NetworkPolicy and the OVN-K8s manifests (delivered separately)
// own pod networking end-to-end.
//
// Unknown CniPlugin values are NOT rejected here — the caller
// (ServerManager) is responsible for the warning + flannel fallback.
// This keeps the applier purely mechanical: typed config in, exec
// out.
func (s *ShellServerApplier) InstallK3sServer(ctx context.Context, cfg BootstrapConfig) error {
	// `curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC=server sh -s - [extra args]`
	// We pipe via `sh -c` to keep it a single exec call; the env var
	// tells the install script to set up server mode. Token + node-
	// name auto-generated by k3s on first boot. Extra args (when
	// non-empty) flow into the systemd unit's `k3s server` argv.
	args, _ := cfg.InstallArgs() // unknown-CNI handling owned by ServerManager
	script := `curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC=server sh -s -`
	if len(args) > 0 {
		// Each arg is appended raw — the K3s install script tokenizes
		// on whitespace inside the resulting ExecStart, so each flag
		// must already be a single shell-safe token. The flags we ship
		// here (--flannel-backend=none, --disable-network-policy) have
		// no whitespace and need no quoting.
		script = script + " " + strings.Join(args, " ")
	}
	_, err := s.execCmd(ctx, "sh", "-c", script)
	return err
}

func (s *ShellServerApplier) IsRunning(ctx context.Context) (bool, error) {
	out, _ := s.execCmd(ctx, "systemctl", "is-active", s.unit())
	return strings.TrimSpace(string(out)) == "active", nil
}

func (s *ShellServerApplier) Start(ctx context.Context) error {
	_, err := s.execCmd(ctx, "systemctl", "start", s.unit())
	return err
}

func (s *ShellServerApplier) Stop(ctx context.Context) error {
	_, err := s.execCmd(ctx, "systemctl", "stop", s.unit())
	return err
}

func (s *ShellServerApplier) Version(ctx context.Context) (string, error) {
	out, err := s.execCmd(ctx, s.Paths.BinaryPath, "--version")
	if err != nil {
		return "", nil // daemon not running / missing — caller treats "" as unknown
	}
	// `k3s --version` outputs:
	//   k3s version v1.30.4+k3s1 (abc1234)
	//   go version go1.22.5
	// We want the first line's third field.
	for _, line := range strings.Split(string(out), "\n") {
		if strings.HasPrefix(line, "k3s version") {
			parts := strings.Fields(line)
			if len(parts) >= 3 {
				return parts[2], nil
			}
		}
	}
	return "", nil
}

func (s *ShellServerApplier) CaptureBootstrapState(_ context.Context) (BootstrapState, error) {
	kubeconfig, err := os.ReadFile(s.Paths.KubeconfigPath)
	if err != nil {
		if os.IsNotExist(err) {
			return BootstrapState{}, nil // not ready yet — defer
		}
		return BootstrapState{}, fmt.Errorf("read kubeconfig: %w", err)
	}
	token, err := os.ReadFile(s.Paths.ServerTokenPath)
	if err != nil {
		if os.IsNotExist(err) {
			return BootstrapState{}, nil
		}
		return BootstrapState{}, fmt.Errorf("read server token: %w", err)
	}
	t := strings.TrimSpace(string(token))
	return BootstrapState{
		Kubeconfig:  string(kubeconfig),
		ServerToken: t,
		AgentToken:  t, // single-cluster v1: same token covers both roles
	}, nil
}

func (s *ShellServerApplier) Cleanup(ctx context.Context) error {
	// k3s ships an uninstall script per role. If it doesn't exist,
	// k3s wasn't installed via the upstream script — bail without
	// error (tolerate "already cleaned up").
	if _, err := os.Stat(s.Paths.UninstallScriptPath); os.IsNotExist(err) {
		return nil
	}
	_, err := s.execCmd(ctx, s.Paths.UninstallScriptPath)
	return err
}

// ShellAgentApplier — production AgentApplier.
//
//   InstallK3sAgent — `curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC=agent sh -s -`
//                     (without K3S_URL/K3S_TOKEN; we write those via
//                      WriteJoinConfig as a systemd drop-in)
//   WriteJoinConfig — atomic write of an Environment= override at
//                     AgentEnvFilePath; daemon-reload to pick it up
//   HasJoinConfig   — stat AgentEnvFilePath; true iff exists + non-zero
//   Cleanup         — exec UninstallAgentPath if present
type ShellAgentApplier struct {
	Paths DaemonPaths
	Unit  string // defaults to "k3s-agent.service"
	Exec  func(ctx context.Context, name string, args ...string) ([]byte, error)
}

func NewShellAgentApplier() *ShellAgentApplier {
	return &ShellAgentApplier{Paths: DefaultPaths, Unit: "k3s-agent.service"}
}

func (s *ShellAgentApplier) unit() string {
	if s.Unit == "" {
		return "k3s-agent.service"
	}
	return s.Unit
}

func (s *ShellAgentApplier) execCmd(ctx context.Context, name string, args ...string) ([]byte, error) {
	if s.Exec != nil {
		return s.Exec(ctx, name, args...)
	}
	cmd := exec.CommandContext(ctx, name, args...)
	out, err := cmd.Output()
	if err != nil {
		var ee *exec.ExitError
		if errors.As(err, &ee) {
			return out, fmt.Errorf("%s %s: %w (stderr: %s)", name,
				strings.Join(args, " "), err, strings.TrimSpace(string(ee.Stderr)))
		}
		return out, fmt.Errorf("%s %s: %w", name, strings.Join(args, " "), err)
	}
	return out, nil
}

func (s *ShellAgentApplier) HasInstalled(_ context.Context) (bool, error) {
	st, err := os.Stat(s.Paths.BinaryPath)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, fmt.Errorf("stat %s: %w", s.Paths.BinaryPath, err)
	}
	return st.Size() > 0, nil
}

func (s *ShellAgentApplier) InstallK3sAgent(ctx context.Context) error {
	script := `curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC=agent sh -s -`
	_, err := s.execCmd(ctx, "sh", "-c", script)
	return err
}

func (s *ShellAgentApplier) IsRunning(ctx context.Context) (bool, error) {
	out, _ := s.execCmd(ctx, "systemctl", "is-active", s.unit())
	return strings.TrimSpace(string(out)) == "active", nil
}

func (s *ShellAgentApplier) Start(ctx context.Context) error {
	_, err := s.execCmd(ctx, "systemctl", "start", s.unit())
	return err
}

func (s *ShellAgentApplier) Stop(ctx context.Context) error {
	_, err := s.execCmd(ctx, "systemctl", "stop", s.unit())
	return err
}

func (s *ShellAgentApplier) Version(ctx context.Context) (string, error) {
	out, err := s.execCmd(ctx, s.Paths.BinaryPath, "--version")
	if err != nil {
		return "", nil
	}
	for _, line := range strings.Split(string(out), "\n") {
		if strings.HasPrefix(line, "k3s version") {
			parts := strings.Fields(line)
			if len(parts) >= 3 {
				return parts[2], nil
			}
		}
	}
	return "", nil
}

func (s *ShellAgentApplier) HasJoinConfig(_ context.Context) (bool, error) {
	st, err := os.Stat(s.Paths.AgentEnvFilePath)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, fmt.Errorf("stat %s: %w", s.Paths.AgentEnvFilePath, err)
	}
	return st.Size() > 0, nil
}

// WriteJoinConfig writes a systemd Environment= drop-in. K3s' agent
// systemd unit reads K3S_URL + K3S_TOKEN from the environment; the
// drop-in mechanism is the canonical Linux way to override a unit's
// env without editing the unit file.
//
// File format:
//   [Service]
//   Environment="K3S_URL=https://[fd00::1]:6443"
//   Environment="K3S_TOKEN=K10agent-tok"
//
// Atomic write: write to .tmp, rename. Daemon-reload after rename so
// systemd picks up the new env on next start.
func (s *ShellAgentApplier) WriteJoinConfig(ctx context.Context, cfg AgentJoinConfig) error {
	if cfg.APIEndpoint == "" || cfg.AgentToken == "" {
		return errors.New("WriteJoinConfig: APIEndpoint + AgentToken required")
	}
	body := fmt.Sprintf(`[Service]
Environment="K3S_URL=%s"
Environment="K3S_TOKEN=%s"
`, cfg.APIEndpoint, cfg.AgentToken)

	dir := filepath.Dir(s.Paths.AgentEnvFilePath)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", dir, err)
	}
	if err := fsutil.AtomicWrite(s.Paths.AgentEnvFilePath, []byte(body), 0o600); err != nil {
		return err
	}
	// Best-effort daemon-reload so the new env is visible before next
	// start. If systemctl fails (test env without systemd), the next
	// `systemctl start` will still work — systemd reads drop-ins on
	// every start.
	_, _ = s.execCmd(ctx, "systemctl", "daemon-reload")
	return nil
}

func (s *ShellAgentApplier) Cleanup(ctx context.Context) error {
	// Remove the env drop-in first (best-effort).
	_ = os.Remove(s.Paths.AgentEnvFilePath)
	// Exec uninstall script if present.
	if _, err := os.Stat(s.Paths.UninstallAgentPath); os.IsNotExist(err) {
		return nil
	}
	_, err := s.execCmd(ctx, s.Paths.UninstallAgentPath)
	return err
}

